name: Auto-triage to project boards

on:
  issues:
    types: [opened, labeled]
  pull_request_target:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COLUMN_NAME: Needs Triage # column where issues will be created

jobs:
  content_project:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 11873277
      PROJECT_NAME: Docs PRs and Issues
    name: Triage to Content Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Content Project
      if: github.event.action == 'opened' && github.event == 'pull_request'
      run: |
        echo "PR!!!!!!!!!!"
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        PR_ID=${{ github.event.pull_request.id }}
        COLUMN=$(gh api -H "$HEADER" projects/$PROJECT_ID/columns --jq ".[] | select(.name == \"$COLUMN_NAME\").id")
        gh api -H "$HEADER" -X POST projects/columns/$COLUMN/cards -f content_type='PullRequest' -F content_id=$PR_ID

    - name: Triages NEW issues and NEW pull requests to the Content Project
      if: github.event.action == 'opened' && github.event == 'issues'
      run: |
        echo "ISSUE!!!!!!!!!!!!"
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        ISSUE_ID=${{ github.event.issue.id }}
        COLUMN=$(gh api -H "$HEADER" projects/$PROJECT_ID/columns --jq ".[] | select(.name == \"$COLUMN_NAME\").id")
        gh api -H "$HEADER" -X POST projects/columns/$COLUMN/cards -f content_type='Issue' -F content_id=$ISSUE_ID


  localization_project:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 12004783
      PROJECT_NAME: Docs Site Localization PRs and Issues
    name: Triage to Localization Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Localization Project
      if: |
        github.event.action == 'labeled' &&
        github.event == 'pull_request' &&
        (contains(github.event.issue.labels.*.name, 'localization') ||
        contains(github.event.pull_request.labels.*.name, 'localization'))
      run: |
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        PR_ID=${{ github.event.pull_request.id }}
        COLUMN=$(gh api -H "$HEADER" projects/$PROJECT_ID/columns --jq ".[] | select(.name == \"$COLUMN_NAME\").id")
        gh api -H "$HEADER" -X POST projects/columns/$COLUMN/cards -f content_type='PullRequest' -F content_id=$PR_ID

    - name: Triages NEW issues and NEW pull requests to the Localization Project
      if: |
        github.event.action == 'labeled' &&
        github.event == 'issues' &&
        (contains(github.event.issue.labels.*.name, 'localization') ||
        contains(github.event.pull_request.labels.*.name, 'localization'))
      run: |
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        ISSUE_ID=${{ github.event.issue.id }}
        COLUMN=$(gh api -H "$HEADER" projects/$PROJECT_ID/columns --jq ".[] | select(.name == \"$COLUMN_NAME\").id")
        gh api -H "$HEADER" -X POST projects/columns/$COLUMN/cards -f content_type='Issue' -F content_id=$ISSUE_ID
